In [1]:
"""
张量 表示一个数值组成的数组, 这个数组可能有多个维度
created by glt 10.07
"""

import torch

x = torch.arange(12)
print(x)
print(x.shape)
print(x.numel()) # number of element 元素的数量

x = x.reshape(3, 4)
print(x)

zo = torch.zeros((2, 3, 4))
one = torch.ones((2, 3, 4))
print(zo)
print(one)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
torch.Size([12])
12
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


In [2]:
# 可以通过提供包含数值的python列表(或嵌套列表)来为所需张量中的每个元素赋予确定值
temp1 = torch.tensor([[2, 1, 4, 3],
                     [1, 2, 3, 4],
                     [4, 3, 2, 1]])
print(temp1)

temp2 = torch.tensor([[[2, 1, 4, 3],
                     [1, 2, 3, 4],
                     [4, 3, 2, 1]]])
print(temp2.shape)  # torch.Size([1, 3, 4])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])
torch.Size([1, 3, 4])


In [3]:
x = torch.tensor([1, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
print(x + y)
print(x - y)
print(x * y)
print(x / y)
print(x ** y)


tensor([ 3,  4,  6, 10])
tensor([-1,  0,  2,  6])
tensor([ 2,  4,  8, 16])
tensor([0.5000, 1.0000, 2.0000, 4.0000])
tensor([ 1,  4, 16, 64])


In [4]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
print(a, b)

# 即使形状不同，仍然可以通过调用广播机制(broadcasting mechanism)来执行按元素操作
# 首先需要a和b维度相同，都是2维数组。把a的1维度复制为2维度，a成3*2的矩阵，b复制为3*2的矩阵，然后再相加
print(a + b)

tensor([[0],
        [1],
        [2]]) tensor([[0, 1]])
tensor([[0, 1],
        [1, 2],
        [2, 3]])


In [5]:
x1 = torch.arange(12, dtype=torch.float32).reshape(3, 4)
x2 = torch.tensor([[2.0, 1, 4, 3],
                   [1, 2, 3, 4],
                   [4, 3, 2, 1]])
print(torch.cat((x1, x2), dim=0)) # dim=0 按行合并
print(torch.cat((x1, x2), dim=1)) # dim=1 按列合并

print(x1 == x2)
print(x1.sum())


# 元素的访问
print(x1[-1])  # 访问最后一行
print(x1[1: 3]) # 访问第1行和第2行

x1[1, 2] = 9
print(x1)
x1[0:2, :] = 12
print(x1)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])
tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])
tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])
tensor(66.)
tensor([ 8.,  9., 10., 11.])
tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])


In [6]:
# 运行一些操作可能会导致为新结果分配内存

X = torch.arange(12, dtype=torch.float32).reshape(3, 4)
Y= torch.tensor([[2.0, 1, 4, 3],
                   [1, 2, 3, 4],
                   [4, 3, 2, 1]])
before = id(Y)
Y = Y + X
id(Y) == before

False

In [7]:
# 执行原地操作
z = torch.zeros_like(Y)
print('id(z): ', id(z))
z[:] = X + Y
print('id(z): ', id(z))

id(z):  140488874811568
id(z):  140488874811568


In [8]:
# 如果在后续计算中没有重复使用X，可以使用X[:] = X + Y 或 X += Y 来减少操作的内存开销
before = id(X)
X += Y
id(X) == before

True

In [9]:
A = X.numpy() # 转换为Numpy张量
B = torch.tensor(A)
print(type(A))
print(type(B))

<class 'numpy.ndarray'>
<class 'torch.Tensor'>


In [10]:
# 将大小为1的张量转换为python标量
a = torch.tensor([3.5])
print(a)
print(a.item())
print(float(a))
print(int(a))

tensor([3.5000])
3.5
3.5
3
